// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var ticker = Ticker.FromJson(jsonString);

namespace CRM.DTO
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public class Ticker 
        [JsonProperty("OrderBookAsks")]
        public List<OrderBook> OrderBookAsks { get; set; }

        [JsonProperty("OrderBookBids")]
        public List<OrderBook> OrderBookBids { get; set; }

        [JsonProperty("TradeHistory")]
        public List<TradeHistory> TradeHistory { get; set; }

        [JsonProperty("TradeDelta")]
        public List<TradeDelta> TradeDelta { get; set; }

        public static Ticker FromJson(string json) => JsonConvert.DeserializeObject<Ticker>(json, Converter.Settings);
    }
    
    public enum Situation { Flat, Trend, Unknown };

    public enum OrderBookAskType { Ask, Bid };

    public enum Side { Buy, Sell };

    public enum TradeHistoryType { Market };
    
}
